<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="helengine.core">
      <HintPath>C:\Users\Helena\AppData\Local\Temp\helengine-builds\7495adff97287b139994a0c587ed9f09\windows\editor-app\publish\helengine.core.dll</HintPath>
    </Reference>
    <Reference Include="helengine.editor">
      <HintPath>C:\Users\Helena\AppData\Local\Temp\helengine-builds\7495adff97287b139994a0c587ed9f09\windows\editor-app\publish\helengine.editor.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
